ShopNetCore/ViewModels/CarsListViewModel.cs
using ShopNetCore.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopNetCore.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> AllCars { get; set; }
        public string currCategory { get; set; }
    }
}

ShopNetCore/ViewModels/HomeViewModel.cs
using ShopNetCore.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopNetCore.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

ShopNetCore/ViewModels/ShopCartViewModel.cs
using ShopNetCore.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopNetCore.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set;}

    }
}

ShopNetCore/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopNetCore.Data.Interfaces;
using ShopNetCore.Data.Models;
using ShopNetCore.ViewModels;

namespace ShopNetCore.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategory;

        public CarsController(IAllCars allCars, ICarsCategory allCategory)
        {
            _allCars = allCars;
            _allCategory = allCategory;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public IActionResult List(string category)
        {
            //ViewBag.Category = "Some New";
            //var cars = _allCars.Cars;

            string _category = category;
            IEnumerable<Car> cars = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(i => i.Id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.CategoryName.Equals("Электромобили")).OrderBy(i => i.Id);
                    currCategory = "Электромобили";
                }
                else if(string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.CategoryName.Equals("Классические автомобили")).OrderBy(i => i.Id);
                    currCategory = "Классические автомобили";
                }                               
            }
            Console.WriteLine();
            var carObj = new CarsListViewModel
            {
                AllCars = cars,
                currCategory = currCategory
            };

            ViewBag.Title = "Страница с автомобилями";
           
            return View(carObj);
        }
    }
}

ShopNetCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopNetCore.Data.Interfaces;
using ShopNetCore.Data.Models;
using ShopNetCore.ViewModels;

namespace ShopNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars _cartRep;


        public HomeController(IAllCars cartRep)
        {
            _cartRep = cartRep;
        }
        public IActionResult Index()
        {
            var homeCars = new HomeViewModel
            {
                favCars = _cartRep.GetFavCars
            };
            return View(homeCars);
        }
    }
}

ShopNetCore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopNetCore.Data.Interfaces;
using ShopNetCore.Data.Models;

namespace ShopNetCore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders _allOrders, ShopCart _shopCart)
        {
            allOrders = _allOrders;
            shopCart = _shopCart;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.ListShopItems = shopCart.getShopItems();
            if (shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("","У Вас должны быть товары");
            }
            if (ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

ShopNetCore/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopNetCore.Data.Interfaces;
using ShopNetCore.Data.Models;
using ShopNetCore.ViewModels;

namespace ShopNetCore.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _cartRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars cartRep, ShopCart shopCart)
        {
            _cartRep = cartRep;
            _shopCart = shopCart;
        }

        public IActionResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _cartRep.Cars.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

ShopNetCore/Views/Cars/List.cshtml
<h1>Все автомобили</h1>
<h3>@Model.currCategory</h3>
@{
    foreach (Car car in Model.AllCars)
    {
        @Html.Partial("AllCars", car)
    }
}

ShopNetCore/Views/Home/Index.cshtml
@model HomeViewModel


<h1 class="mb-4">Лучшие автомобили</h1>

@{
    foreach (Car car in Model.favCars)
    {
        @Html.Partial("AllCars", car)
    }
}

ShopNetCore/Views/Order/Checkout.cshtml
@model Order

    <h3 class="mt-4">Оформление заказа</h3>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Checkout" method="post" class="form-horizontal">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Surname"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Adress"></label>
                    <input asp-for="Adress" class="form-control" />
                    <span asp-validation-for="Adress" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Phone"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <input class="btn btn-success" type="submit" value="Завершить заказ" />
            </form>
        </div>
    </div>

ShopNetCore/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

ShopNetCore/Views/Shared/AllCars.cshtml
@model Car

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">
            @Model.Price.ToString("c") <span class="text-muted">@Model.Name</span>
            <a class="btn btn-outline-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.Id">Добавить в корзину</a>
        </h2>
        <p class="lead">
            @Model.ShortDesc

        </p>
    </div>
    <div class="col-md-5">
        <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"
             width="500" height="500" src="@Model.Img" alt="@Model.Name" />
    </div>

</div>

<hr class="featurette-divider">

ShopNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Лучшие автомобили <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cars" asp-action="List">Машины</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Cars/List/fuel">Классические автомобили</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Cars/List/electro">Электромобили</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ShopCart/">Корзина</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5 mb-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017-2019 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

ShopNetCore/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container">
    @foreach (var el in Model.shopCart.ListShopItems)
    {
    <div class="alert alert-warning mt-3">
        <b>Автомобиль:</b> @el.car.Name<br />
        <b>Цена:</b> @el.car.Price.ToString("c")
    </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>   
</div>